export const categories = [
  "Pain Relief",
  "Vitamins & Supplements",
  "Cold & Flu",
  "Diabetes Care",
  "Skin Care",
  "First Aid",
  "Feminine Intimate Cleanser",
  "Infertility",
  "Powerful Multivitamin",
  "Coenzyme Q10 50mg + 100mg",
  "Skin and Nipple Ointment",
  "Melatonin",
  "ferrous bisglycinate + Folic Acid + Vitamic C",
  "L-methylfolate",
  "Coenzyme Q10 50mg Soft Gell",
  "Relieves Headache, Cold & Flu Chest Congestion",
  "Pain Relief Gel",
  "Low Sodium Salt Substitute",
  "Antacid Syrup",
];
